CREATE TABLE `dim_arrest_borough`  (
  `borough_sk` int NOT NULL AUTO_INCREMENT,
  `boro_code` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `borough` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_JobID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NOT NULL DEFAULT 'now()',
  PRIMARY KEY (`borough_sk`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_BODILY_INJURY`  (
  `BODILY_INJURY_SK` int NOT NULL AUTO_INCREMENT,
  `BODILY_INJURY` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`BODILY_INJURY_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_COMPLAINT`  (
  `COMPLAINT_SK` int NOT NULL AUTO_INCREMENT,
  `COMPLAINT` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`COMPLAINT_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_CONTRIBUTING_FACTOR`  (
  `CONTRIBUTING_FACTOR_SK` int NOT NULL AUTO_INCREMENT,
  `CONTRIBUTING_FACTOR` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`CONTRIBUTING_FACTOR_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_DRIVER_LICENSE_JURISDICTION`  (
  `DRIVER_LICENSE_JURISDICTION_SK` int NOT NULL AUTO_INCREMENT,
  `DRIVER_LICENSE_JURISDICTION` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`DRIVER_LICENSE_JURISDICTION_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_DRIVER_LICENSE_STATUS`  (
  `DRIVER_LICENSE_STATUS_SK` int NOT NULL AUTO_INCREMENT,
  `DRIVER_LICENSE_STATUS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`DRIVER_LICENSE_STATUS_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_EJECTION`  (
  `EJECTION_SK` int NOT NULL AUTO_INCREMENT,
  `EJECTION` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`EJECTION_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_EMOTIONAL_STATUS`  (
  `EMOTIONAL_STATUS_SK` int NOT NULL AUTO_INCREMENT,
  `EMOTIONAL_STATUS` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`EMOTIONAL_STATUS_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_PED_ACTION`  (
  `PED_ACTION_SK` int NOT NULL AUTO_INCREMENT,
  `PED_ACTION` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`PED_ACTION_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_PED_LOCATION`  (
  `PED_LOCATION_SK` int NOT NULL AUTO_INCREMENT,
  `PED_LOCATION` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`PED_LOCATION_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_PED_ROLE`  (
  `PED_ROLE_SK` int NOT NULL AUTO_INCREMENT,
  `PED_ROLE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`PED_ROLE_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_PERSON_INJURY`  (
  `PERSON_INJURY_SK` int NOT NULL AUTO_INCREMENT,
  `PERSON_INJURY` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`PERSON_INJURY_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_PERSON_SEX`  (
  `PERSON_SEX_SK` int NOT NULL AUTO_INCREMENT,
  `PERSON_SEX` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`PERSON_SEX_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_PersonType`  (
  `PERSON_TYPE_SK` int NOT NULL AUTO_INCREMENT,
  `PERSON_TYPE` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`PERSON_TYPE_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_POINT_OF_IMPACT`  (
  `POINT_OF_IMPACT_SK` int NOT NULL AUTO_INCREMENT,
  `POINT_OF_IMPACT` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`POINT_OF_IMPACT_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_POSITION_IN_VEHICLE`  (
  `POSITION_IN_VEHICLE_SK` int NOT NULL AUTO_INCREMENT,
  `POSITION_IN_VEHICLE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`POSITION_IN_VEHICLE_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_PRE_CRASH`  (
  `PRE_CRASH_SK` int NOT NULL AUTO_INCREMENT,
  `PRE_CRASH` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`PRE_CRASH_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_PUBLIC_PROPERTY_DAMAGE`  (
  `PUBLIC_PROPERTY_DAMAGE_SK` int NOT NULL AUTO_INCREMENT,
  `PUBLIC_PROPERTY_DAMAGE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`PUBLIC_PROPERTY_DAMAGE_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_SAFETY_EQUIPMENT`  (
  `SAFETY_EQUIPMENT_SK` int NOT NULL AUTO_INCREMENT,
  `SAFETY_EQUIPMENT` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`SAFETY_EQUIPMENT_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_STATE_REGISTRATION`  (
  `STATE_REGISTRATION_SK` int NOT NULL AUTO_INCREMENT,
  `STATE_REGISTRATION` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`STATE_REGISTRATION_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_TRAVEL_DIRECTION`  (
  `TRAVEL_DIRECTION_SK` int NOT NULL AUTO_INCREMENT,
  `TRAVEL_DIRECTION` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`TRAVEL_DIRECTION_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_VEHICLE_DAMAGE`  (
  `VEHICLE_DAMAGE_SK` int NOT NULL AUTO_INCREMENT,
  `VEHICLE_DAMAGE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`VEHICLE_DAMAGE_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_VEHICLE_MAKE`  (
  `VEHICLE_MAKE_SK` int NOT NULL AUTO_INCREMENT,
  `VEHICLE_MAKE` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`VEHICLE_MAKE_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_VEHICLE_MODEL`  (
  `VEHICLE_MODEL_SK` int NOT NULL AUTO_INCREMENT,
  `VEHICLE_MODEL` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`VEHICLE_MODEL_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `Dim_VEHICLE_TYPE`  (
  `VEHICLE_TYPE_SK` int NOT NULL AUTO_INCREMENT,
  `VEHICLE_TYPE` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`VEHICLE_TYPE_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `dim_vehicle_type_code`  (
  `vehicle_type_code_SK` int NOT NULL AUTO_INCREMENT,
  `vehicle_type_code` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_JobID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NOT NULL DEFAULT 'now()',
  PRIMARY KEY (`vehicle_type_code_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `ERR_Model_Year`  (
  `UNIQUE_ID` int NULL DEFAULT NULL,
  `COLLISION_ID` int NULL DEFAULT NULL,
  `CRASH_DATE` datetime NULL DEFAULT NULL,
  `VEHICLE_YEAR` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `fct_collision_crashes`  (
  `collision_sk` bigint NOT NULL,
  `collision_id` bigint NULL DEFAULT NULL,
  `collision_dt` datetime NULL DEFAULT NULL,
  `collision_dt_sk` int NULL DEFAULT NULL,
  `collision_day` date NULL DEFAULT NULL,
  `collision_time` time NULL DEFAULT NULL,
  `collision_hour` int NULL DEFAULT NULL,
  `collision_dayoftheweek` int NULL DEFAULT NULL,
  `borough_sk` int NULL DEFAULT NULL,
  `borough` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `zip_code` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `off_street_name` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `on_street_name` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `cross_street_name` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `latitude` decimal(24, 6) NULL DEFAULT NULL,
  `longitude` decimal(24, 6) NULL DEFAULT NULL,
  `location` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `number_of_cyclist_injured` int NULL DEFAULT NULL,
  `number_of_cyclist_killed` int NULL DEFAULT NULL,
  `number_of_motorist_injured` int NULL DEFAULT NULL,
  `number_of_motorist_killed` int NULL DEFAULT NULL,
  `number_of_pedestrians_injured` int NULL DEFAULT NULL,
  `number_of_pedestrians_killed` int NULL DEFAULT NULL,
  `number_of_persons_injured` int NULL DEFAULT NULL,
  `number_of_persons_killed` int NULL DEFAULT NULL,
  `number_of_vehicles_involved` int NULL DEFAULT NULL,
  `number_of_contributing_factors` int NULL DEFAULT NULL,
  `DI_JobID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`collision_sk`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `fct_collision_crashes_vehicles`  (
  `collision_sk` bigint NOT NULL,
  `collision_id` bigint NOT NULL,
  `Vehicle_number` int NOT NULL,
  `vehicle_type_code_SK` int NULL DEFAULT NULL,
  `contributing_factor_vehicle_sk` int NOT NULL,
  `DI_JobID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NOT NULL DEFAULT 'now()',
  PRIMARY KEY (`collision_sk`, `Vehicle_number`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `fct_collision_persons`  (
  `UNIQUE_ID` int NOT NULL,
  `COLLISION_ID` int NULL DEFAULT NULL,
  `PERSON_ID` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `PERSON_TYPE_SK` int NOT NULL,
  `PERSON_INJURY_SK` int NOT NULL,
  `VEHICLE_ID` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `PERSON_AGE` int NULL DEFAULT NULL,
  `EJECTION_SK` int NOT NULL,
  `EMOTIONAL_STATUS_SK` int NOT NULL,
  `BODILY_INJURY_SK` int NOT NULL,
  `POSITION_IN_VEHICLE_SK` int NOT NULL,
  `SAFETY_EQUIPMENT_SK` int NOT NULL,
  `PED_LOCATION_SK` int NOT NULL,
  `PED_ACTION_SK` int NOT NULL,
  `COMPLAINT_SK` int NOT NULL,
  `PED_ROLE_SK` int NOT NULL,
  `PERSON_SEX_SK` int NOT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`UNIQUE_ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `fct_collision_persons_contributing_factors`  (
  `TABLE_SK` int NOT NULL AUTO_INCREMENT,
  `UNIQUE_ID` int NOT NULL,
  `COLLISION_ID` int NULL DEFAULT NULL,
  `PERSON_ID` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `FACTOR_NUMBER` int NULL DEFAULT NULL,
  `CONTRIBUTING_FACTOR_SK` int NOT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NULL DEFAULT 'now()',
  PRIMARY KEY (`TABLE_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `fct_Collisions_Vehicles`  (
  `UNIQUE_ID` int NOT NULL,
  `COLLISION_ID` int NULL DEFAULT NULL,
  `VEHICLE_ID` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `STATE_REGISTRATION_SK` int NOT NULL,
  `VEHICLE_TYPE_SK` int NOT NULL,
  `VEHICLE_MAKE_SK` int NOT NULL,
  `VEHICLE_MODEL_SK` int NOT NULL,
  `VEHICLE_YEAR` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `TRAVEL_DIRECTION_SK` int NOT NULL,
  `VEHICLE_OCCUPANTS` int NULL DEFAULT NULL,
  `PERSON_SEX_SK` int NOT NULL,
  `DRIVER_LICENSE_STATUS_SK` int NOT NULL,
  `DRIVER_LICENSE_JURISDICTION_SK` int NOT NULL,
  `PRE_CRASH_SK` int NOT NULL,
  `POINT_OF_IMPACT_SK` int NOT NULL,
  `PUBLIC_PROPERTY_DAMAGE_SK` int NOT NULL,
  `PUBLIC_PROPERTY_DAMAGE_TYPE` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NOT NULL DEFAULT 'now()',
  PRIMARY KEY (`UNIQUE_ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `fct_Collisions_Vehicles_Contributing_Factors`  (
  `TABLE_SK` int NOT NULL AUTO_INCREMENT,
  `UNIQUE_ID` int NOT NULL,
  `COLLISION_ID` int NULL DEFAULT NULL,
  `VEHICLE_ID` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `VEHICLE_CONTRIBUTING_NUMBER` int NULL DEFAULT NULL,
  `CONTRIBUTING_FACTOR_SK` int NOT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NOT NULL DEFAULT 'now()',
  PRIMARY KEY (`TABLE_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

CREATE TABLE `fct_Collisions_Vehicles_Vehicle_Damage`  (
  `TABLE_SK` int NOT NULL AUTO_INCREMENT,
  `UNIQUE_ID` int NOT NULL,
  `COLLISION_ID` int NULL DEFAULT NULL,
  `VEHICLE_ID` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `VEHICLE_DAMAGE_NUMBER` int NULL DEFAULT NULL,
  `VEHICLE_DAMAGE_SK` int NOT NULL,
  `DI_PID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `DI_Create_Date` datetime NOT NULL DEFAULT 'now()',
  PRIMARY KEY (`TABLE_SK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

ALTER TABLE `fct_collision_crashes` ADD CONSTRAINT `collision_sk` FOREIGN KEY (`collision_sk`) REFERENCES `fct_collision_crashes_vehicles` ();
ALTER TABLE `fct_collision_crashes` ADD CONSTRAINT `borough_sk` FOREIGN KEY (`borough_sk`) REFERENCES `dim_arrest_borough` ();
ALTER TABLE `fct_collision_crashes` ADD CONSTRAINT `collision_id` FOREIGN KEY (`collision_id`) REFERENCES `fct_collision_persons` ();
ALTER TABLE `fct_collision_crashes_vehicles` ADD CONSTRAINT `collision_sk` FOREIGN KEY (`collision_sk`) REFERENCES `fct_collision_crashes_vehicles` ();
ALTER TABLE `fct_collision_crashes_vehicles` ADD CONSTRAINT `vehicle_type_code_SK` FOREIGN KEY (`vehicle_type_code_SK`) REFERENCES `dim_vehicle_type_code` ();
ALTER TABLE `fct_collision_crashes_vehicles` ADD CONSTRAINT `collision_id` FOREIGN KEY (`collision_id`) REFERENCES `fct_collision_persons` ();
ALTER TABLE `fct_collision_persons` ADD CONSTRAINT `PERSON_TYPE_SK` FOREIGN KEY (`PERSON_TYPE_SK`) REFERENCES `Dim_PersonType` ();
ALTER TABLE `fct_collision_persons` ADD CONSTRAINT `PERSON_INJURY_SK` FOREIGN KEY (`PERSON_INJURY_SK`) REFERENCES `Dim_PERSON_INJURY` ();
ALTER TABLE `fct_collision_persons` ADD CONSTRAINT `EJECTION_SK` FOREIGN KEY (`EJECTION_SK`) REFERENCES `Dim_EJECTION` ();
ALTER TABLE `fct_collision_persons` ADD CONSTRAINT `BODILY_INJURY_SK` FOREIGN KEY (`BODILY_INJURY_SK`) REFERENCES `Dim_BODILY_INJURY` ();
ALTER TABLE `fct_collision_persons` ADD CONSTRAINT `POSITION_IN_VEHICLE_SK` FOREIGN KEY (`POSITION_IN_VEHICLE_SK`) REFERENCES `Dim_POSITION_IN_VEHICLE` ();
ALTER TABLE `fct_collision_persons` ADD CONSTRAINT `SAFETY_EQUIPEMENT_SK` FOREIGN KEY (`SAFETY_EQUIPMENT_SK`) REFERENCES `Dim_SAFETY_EQUIPMENT` ();
ALTER TABLE `fct_collision_persons` ADD CONSTRAINT `PED_LOCATION_SK` FOREIGN KEY (`PED_LOCATION_SK`) REFERENCES `Dim_PED_LOCATION` ();
ALTER TABLE `fct_collision_persons` ADD CONSTRAINT `PED_ACTION_SK` FOREIGN KEY (`PED_ACTION_SK`) REFERENCES `Dim_PED_ACTION` ();
ALTER TABLE `fct_collision_persons` ADD CONSTRAINT `COMPLAINT_SK` FOREIGN KEY (`COMPLAINT_SK`) REFERENCES `Dim_COMPLAINT` ();
ALTER TABLE `fct_collision_persons` ADD CONSTRAINT `PED_ROLE_SK` FOREIGN KEY (`PED_ROLE_SK`) REFERENCES `Dim_PED_ROLE` ();
ALTER TABLE `fct_collision_persons` ADD CONSTRAINT `PERSON_SEX_SK` FOREIGN KEY (`PERSON_SEX_SK`) REFERENCES `Dim_PERSON_SEX` ();
ALTER TABLE `fct_collision_persons` ADD CONSTRAINT `EMOTIONAL_STATUS_SK` FOREIGN KEY (`EMOTIONAL_STATUS_SK`) REFERENCES `Dim_EMOTIONAL_STATUS` ();
ALTER TABLE `fct_collision_persons` ADD CONSTRAINT `UNIQUE_ID` FOREIGN KEY (`UNIQUE_ID`) REFERENCES `fct_collision_persons` ();
ALTER TABLE `fct_collision_persons_contributing_factors` ADD CONSTRAINT `CONTRIBUTING_FACTOR_SK` FOREIGN KEY (`CONTRIBUTING_FACTOR_SK`) REFERENCES `Dim_CONTRIBUTING_FACTOR` ();
ALTER TABLE `fct_collision_persons_contributing_factors` ADD CONSTRAINT `COLLISION_ID` FOREIGN KEY (`COLLISION_ID`) REFERENCES `ERR_Model_Year` ();
ALTER TABLE `fct_collision_persons_contributing_factors` ADD CONSTRAINT `UNIQUE_ID` FOREIGN KEY (`UNIQUE_ID`) REFERENCES `fct_collision_persons` ();
ALTER TABLE `fct_Collisions_Vehicles` ADD CONSTRAINT `STATE_REGISTRATION_SK` FOREIGN KEY (`STATE_REGISTRATION_SK`) REFERENCES `Dim_STATE_REGISTRATION` ();
ALTER TABLE `fct_Collisions_Vehicles` ADD CONSTRAINT `VEHICLE_TYPE_SK` FOREIGN KEY (`VEHICLE_TYPE_SK`) REFERENCES `Dim_VEHICLE_TYPE` ();
ALTER TABLE `fct_Collisions_Vehicles` ADD CONSTRAINT `VEHICLE_MAKE_SK` FOREIGN KEY (`VEHICLE_MAKE_SK`) REFERENCES `Dim_VEHICLE_MAKE` ();
ALTER TABLE `fct_Collisions_Vehicles` ADD CONSTRAINT `VEHICLE_MODEL_SK` FOREIGN KEY (`VEHICLE_MODEL_SK`) REFERENCES `Dim_VEHICLE_MODEL` ();
ALTER TABLE `fct_Collisions_Vehicles` ADD CONSTRAINT `TRAVEL_DIRECTION_SK` FOREIGN KEY (`TRAVEL_DIRECTION_SK`) REFERENCES `Dim_TRAVEL_DIRECTION` ();
ALTER TABLE `fct_Collisions_Vehicles` ADD CONSTRAINT `PERSON_SEX_SK` FOREIGN KEY (`PERSON_SEX_SK`) REFERENCES `Dim_PERSON_SEX` ();
ALTER TABLE `fct_Collisions_Vehicles` ADD CONSTRAINT `DRIVER_LICENSE_STATUS_SK` FOREIGN KEY (`DRIVER_LICENSE_STATUS_SK`) REFERENCES `Dim_DRIVER_LICENSE_STATUS` ();
ALTER TABLE `fct_Collisions_Vehicles` ADD CONSTRAINT `DRIVER_LICENSE_JUSRISDICTION_SK` FOREIGN KEY (`DRIVER_LICENSE_JURISDICTION_SK`) REFERENCES `Dim_DRIVER_LICENSE_JURISDICTION` ();
ALTER TABLE `fct_Collisions_Vehicles` ADD CONSTRAINT `PRE_CRASH_SK` FOREIGN KEY (`PRE_CRASH_SK`) REFERENCES `Dim_PRE_CRASH` ();
ALTER TABLE `fct_Collisions_Vehicles` ADD CONSTRAINT `POINT_OF_IMPACT_SK` FOREIGN KEY (`POINT_OF_IMPACT_SK`) REFERENCES `Dim_POINT_OF_IMPACT` ();
ALTER TABLE `fct_Collisions_Vehicles` ADD CONSTRAINT `PUBLIC_PROPERTY_DAMAGE_SK` FOREIGN KEY (`PUBLIC_PROPERTY_DAMAGE_SK`) REFERENCES `Dim_PUBLIC_PROPERTY_DAMAGE` ();
ALTER TABLE `fct_Collisions_Vehicles_Contributing_Factors` ADD CONSTRAINT `CONTRIBUTING_FACTOR_SK` FOREIGN KEY (`CONTRIBUTING_FACTOR_SK`) REFERENCES `Dim_CONTRIBUTING_FACTOR` ();
ALTER TABLE `fct_Collisions_Vehicles_Contributing_Factors` ADD CONSTRAINT `UNIQUE_ID` FOREIGN KEY (`UNIQUE_ID`) REFERENCES `fct_collision_persons` ();
ALTER TABLE `fct_Collisions_Vehicles_Vehicle_Damage` ADD CONSTRAINT `VEHICLE_DAMAGE_SK` FOREIGN KEY (`VEHICLE_DAMAGE_SK`) REFERENCES `Dim_VEHICLE_DAMAGE` ();
ALTER TABLE `fct_Collisions_Vehicles_Vehicle_Damage` ADD CONSTRAINT `UNIQUE_ID` FOREIGN KEY (`UNIQUE_ID`) REFERENCES `fct_collision_persons` ();

